components:
  schemas:
    BuildingGeoCordsResponse:
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/BuildingGeoCordsResponseData'
          description: Данные ответа
          title: Data
      required:
      - data
      title: BuildingGeoCordsResponse
      type: object
    BuildingGeoCordsResponseData:
      description: Данные ответа
      properties:
        pointLat:
          description: Широта
          title: Pointlat
          type: string
        pointLon:
          description: Долгота
          title: Pointlon
          type: string
      required:
      - pointLon
      - pointLat
      title: BuildingGeoCordsResponseData
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    TraceCopper:
      description: Данные трассировки по медной сети
      properties:
        parentContainerExternalId:
          description: ID родительского физического контейнера во внешней системе
          example: 13
          title: Parentcontainerexternalid
          type: integer
        townStateId:
          description: Населенный пункт_ID
          example: 2
          title: Townstateid
          type: integer
      title: TraceCopper
      type: object
    TraceOptical:
      description: Данные трассировки по оптической сети
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/TraceOpticalData'
          description: Данные ответа
          title: Data
      required:
      - data
      title: TraceOptical
      type: object
    TraceOpticalData:
      description: Данные ответа
      properties:
        lineData:
          description: Строка линейных данных
          example: 'TOWN:727;STATION:40/01; MAN:ECI; OLT:3/00/06/06;ODF:2/08/09/06;
            LD:ОРШ 223/37: 00/00/1 магистраль/6, 00/00/2 сплиттеры /16, 00/00/2 сплиттеры
            /18, 00/00/5 распределение/12; ОРКсп 223/37/6/2: 00/00/1х16/11 (Этаж 5);
            OU:0;ONUPORTNUM:0; (DSL,SIP); 3.542 км'
          title: Linedata
          type: string
      required:
      - lineData
      title: TraceOpticalData
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  contact:
    email: japparov.s@telecom.kz
    name: Shakhmurat Japparov
  description: Сервисы VCIP
  title: vcip-api
  version: '1.0'
openapi: 3.0.0
paths:
  /building-geo-cords:
    get:
      description: Метод возвращает геокоординаты здания по параметрам
      operationId: get_building_geo_cords_building_geo_cords_get
      parameters:
      - description: Населенный пункт_ID
        in: query
        name: townStateId
        required: true
        schema:
          description: Населенный пункт_ID
          title: Townstateid
          type: integer
      - description: Улица_ID
        in: query
        name: streetId
        required: true
        schema:
          description: Улица_ID
          title: Streetid
          type: integer
      - description: Номер здания
        in: query
        name: buildingNum
        required: true
        schema:
          description: Номер здания
          title: Buildingnum
          type: integer
      - description: Дробь здания
        in: query
        name: buildingSubNum
        required: false
        schema:
          description: Дробь здания
          title: Buildingsubnum
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingGeoCordsResponse'
          description: OK
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Получить геокоординаты здания
      tags:
      - Геокоординаты
  /trace-copper:
    get:
      description: Получить трассировку по медной сети
      operationId: get_trace_copper_trace_copper_get
      parameters:
      - description: Населенный пункт_ID
        in: query
        name: townStateId
        required: true
        schema:
          description: Населенный пункт_ID
          title: Townstateid
          type: number
      - description: ID физического контейнера во внешней системе
        in: query
        name: containerExternalId
        required: true
        schema:
          description: ID физического контейнера во внешней системе
          title: Containerexternalid
          type: number
      - description: Номер монтированного порта
        in: query
        name: mountedPortNum
        required: true
        schema:
          description: Номер монтированного порта
          title: Mountedportnum
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceCopper'
          description: OK
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Получить трассировку по медной сети
      tags:
      - Трассировка по медной сети
  /trace-optical:
    get:
      description: Получить трассировку по оптической сети
      operationId: get_trace_optical_trace_optical_get
      parameters:
      - description: Населенный пункт_ID
        in: query
        name: townStateId
        required: true
        schema:
          description: Населенный пункт_ID
          title: Townstateid
          type: number
      - description: Спецификация физического контейнера_ID
        in: query
        name: containerSpecId
        required: true
        schema:
          description: Спецификация физического контейнера_ID
          title: Containerspecid
          type: number
      - description: ID физического контейнера во внешней системе
        in: query
        name: containerExternalId
        required: true
        schema:
          description: ID физического контейнера во внешней системе
          title: Containerexternalid
          type: number
      - description: Номер монтированного порта
        in: query
        name: mountedPortNum
        required: true
        schema:
          description: Номер монтированного порта
          title: Mountedportnum
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceOptical'
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
        '500':
          description: Internal Server Error
      summary: Получить трассировку по оптической сети
      tags:
      - Трассировка по оптической сети
servers:
- description: test
  url: http://localhost:3000/api/vcip-api/v1.0
