components:
  schemas:
    BuildingGeoCordsGetResponse:
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/Data1'
          description: "\u0414\u0430\u043D\u043D\u044B\u0435 \u043E\u0442\u0432\u0435\
            \u0442\u0430"
          title: Data
      required:
      - data
      title: BuildingGeoCordsGetResponse
      type: object
    Data:
      properties:
        lineData:
          description: "\u0421\u0442\u0440\u043E\u043A\u0430 \u043B\u0438\u043D\u0435\
            \u0439\u043D\u044B\u0445 \u0434\u0430\u043D\u043D\u044B\u0445"
          example: "TOWN:727;STATION:40/01; MAN:ECI; OLT:3/00/06/06;ODF:2/08/09/06;\
            \ LD:\u041E\u0420\u0428 223/37: 00/00/1 \u043C\u0430\u0433\u0438\u0441\
            \u0442\u0440\u0430\u043B\u044C/6, 00/00/2 \u0441\u043F\u043B\u0438\u0442\
            \u0442\u0435\u0440\u044B /16, 00/00/2 \u0441\u043F\u043B\u0438\u0442\u0442\
            \u0435\u0440\u044B /18, 00/00/5 \u0440\u0430\u0441\u043F\u0440\u0435\u0434\
            \u0435\u043B\u0435\u043D\u0438\u0435/12; \u041E\u0420\u041A\u0441\u043F\
            \ 223/37/6/2: 00/00/1\u044516/11 (\u042D\u0442\u0430\u0436 5); OU:0;ONUPORTNUM:0;\
            \ (DSL,SIP); 3.542 \u043A\u043C"
          title: Linedata
          type: string
      required:
      - lineData
      title: Data
      type: object
    Data1:
      properties:
        pointLat:
          description: "\u0428\u0438\u0440\u043E\u0442\u0430"
          title: Pointlat
          type: string
        pointLon:
          description: "\u0414\u043E\u043B\u0433\u043E\u0442\u0430"
          title: Pointlon
          type: string
      required:
      - pointLon
      - pointLat
      title: Data1
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    TraceCopper:
      properties:
        parentContainerExternalId:
          description: "ID \u0440\u043E\u0434\u0438\u0442\u0435\u043B\u044C\u0441\u043A\
            \u043E\u0433\u043E \u0444\u0438\u0437\u0438\u0447\u0435\u0441\u043A\u043E\
            \u0433\u043E \u043A\u043E\u043D\u0442\u0435\u0439\u043D\u0435\u0440\u0430\
            \ \u0432\u043E \u0432\u043D\u0435\u0448\u043D\u0435\u0439 \u0441\u0438\
            \u0441\u0442\u0435\u043C\u0435"
          example: 13
          title: Parentcontainerexternalid
          type: integer
        townStateId:
          description: "\u041D\u0430\u0441\u0435\u043B\u0435\u043D\u043D\u044B\u0439\
            \ \u043F\u0443\u043D\u043A\u0442_ID"
          example: 2
          title: Townstateid
          type: integer
      title: TraceCopper
      type: object
    TraceOptical:
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/Data'
          description: "\u0414\u0430\u043D\u043D\u044B\u0435 \u043E\u0442\u0432\u0435\
            \u0442\u0430"
          title: Data
      required:
      - data
      title: TraceOptical
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  contact:
    email: japparov.s@telecom.kz
    name: Shakhmurat Japparov
  description: "\u0421\u0435\u0440\u0432\u0438\u0441\u044B VCIP"
  title: vcip-api
  version: 3.0.0
openapi: 3.1.0
paths:
  /building-geo-cords:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0433\u0435\u043E\
        \u043A\u043E\u043E\u0440\u0434\u0438\u043D\u0430\u0442\u044B \u0437\u0434\u0430\
        \u043D\u0438\u044F"
      operationId: get_building_geo_cords_building_geo_cords_get
      parameters:
      - in: query
        name: townStateId
        required: true
        schema:
          title: Townstateid
          type: integer
      - in: query
        name: streetId
        required: true
        schema:
          title: Streetid
          type: integer
      - in: query
        name: buildingNum
        required: true
        schema:
          title: Buildingnum
          type: integer
      - in: query
        name: buildingSubNum
        required: false
        schema:
          title: Buildingsubnum
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingGeoCordsGetResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Building Geo Cords
      tags:
      - "\u0413\u0435\u043E\u043A\u043E\u043E\u0440\u0434\u0438\u043D\u0430\u0442\u044B"
  /trace-copper:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0442\u0440\u0430\
        \u0441\u0441\u0438\u0440\u043E\u0432\u043A\u0443 \u043F\u043E \u043C\u0435\
        \u0434\u043D\u043E\u0439 \u0441\u0435\u0442\u0438"
      operationId: get_trace_copper_trace_copper_get
      parameters:
      - in: query
        name: townStateId
        required: true
        schema:
          title: Townstateid
          type: number
      - in: query
        name: containerExternalId
        required: true
        schema:
          title: Containerexternalid
          type: number
      - in: query
        name: mountedPortNum
        required: true
        schema:
          title: Mountedportnum
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceCopper'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Trace Copper
      tags:
      - "\u0422\u0440\u0430\u0441\u0441\u0438\u0440\u043E\u0432\u043A\u0430 \u043F\
        \u043E \u043C\u0435\u0434\u043D\u043E\u0439 \u0441\u0435\u0442\u0438"
  /trace-optical:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0442\u0440\u0430\
        \u0441\u0441\u0438\u0440\u043E\u0432\u043A\u0443 \u043F\u043E \u043E\u043F\
        \u0442\u0438\u0447\u0435\u0441\u043A\u043E\u0439 \u0441\u0435\u0442\u0438"
      operationId: get_trace_optical_trace_optical_get
      parameters:
      - in: query
        name: townStateId
        required: true
        schema:
          title: Townstateid
          type: number
      - in: query
        name: containerSpecId
        required: true
        schema:
          title: Containerspecid
          type: number
      - in: query
        name: containerExternalId
        required: true
        schema:
          title: Containerexternalid
          type: number
      - in: query
        name: mountedPortNum
        required: true
        schema:
          title: Mountedportnum
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceOptical'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Trace Optical
      tags:
      - "\u0422\u0440\u0430\u0441\u0441\u0438\u0440\u043E\u0432\u043A\u0430 \u043F\
        \u043E \u043E\u043F\u0442\u0438\u0447\u0435\u0441\u043A\u043E\u0439 \u0441\
        \u0435\u0442\u0438"
servers:
- description: test
  url: !!python/object/new:pydantic.networks.AnyUrl
    args:
    - http://localhost:3000/api/vcip-api/v1.0
    state: !!python/tuple
    - null
    - fragment: null
      host: localhost
      host_type: int_domain
      password: null
      path: /api/vcip-api/v1.0
      port: '3000'
      query: null
      scheme: http
      tld: null
      user: null
