# generated by fastapi-codegen:
#   filename:  phone-activate-be.yaml
#   timestamp: 2023-10-10T11:40:16+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional, Union

from fastapi import FastAPI, Query
from pydantic import conint, constr

from .models import (
    AutoActivateListResponse,
    BaseResponse,
    CountModel,
    IsFalloutType,
    PhoneActivateFullResponse,
    PhoneActivateHistoryListResponse,
    PhoneActivateListRequest,
    PhoneActivateSearchListResponse,
    PhoneAssignRequest,
    PhoneAutomatiSetDoneRequest,
    PhoneAutomatiSetFalloutRequest,
    PhoneChangeFxsLoginPwd,
    PhoneManualExecuteRequest,
    PhoneRepeatAutoRequest,
    RefExchangeListResponse,
    RefTownStateList,
    RefVendorModelList,
    RejectReasonList,
)

app = FastAPI(
    version='1.0',
    title='phone-activate-be',
    summary='MODE=TEST, TAG=0.0, PIPELINE_ID=0000',
    description='Микросервис активации Телефонии на ЦАТС/SWW в ручном или автоматическом режиме.',
    termsOfService='http://example.com/terms',
    contact={
        'name': 'VVT Group LLP',
        'url': 'http://www.kt.kz/',
        'email': 'info@vvt.kz',
    },
    license={
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
        'name': 'Apache 2.0',
    },
)


@app.post(
    '/api/phone-activate-be/v1.0/assign-request',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def do_assign_phone_activation_request_api_phone_activate_be_v1_0_assign_request_post(
    body: PhoneAssignRequest,
) -> BaseResponse:
    """
    Do Assign Phone Activation Request
    """
    pass


@app.post(
    '/api/phone-activate-be/v1.0/change-fxs-data',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def do_change_phone_activation_fxs_data_api_phone_activate_be_v1_0_change_fxs_data_post(
    body: PhoneChangeFxsLoginPwd,
) -> BaseResponse:
    """
    Do Change Phone Activation Fxs Data
    """
    pass


@app.post(
    '/api/phone-activate-be/v1.0/create-request',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['BPM OSM/WFM'],
)
def do_create_phone_activation_request_api_phone_activate_be_v1_0_create_request_post(
    body: PhoneActivateListRequest,
) -> BaseResponse:
    """
    Do Create Phone Activation Request
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-history',
    response_model=PhoneActivateHistoryListResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_phone_activation_history_api_phone_activate_be_v1_0_get_history_get(
    phone_activate_id: conint(ge=0) = Query(..., alias='phoneActivateId')
) -> Union[PhoneActivateHistoryListResponse, BaseResponse]:
    """
    Get Phone Activation History
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-new-requests-by-exchange-id-list',
    response_model=AutoActivateListResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['BPM activate-phone'],
)
def get_new_requests_by_exchange_id_list_api_phone_activate_be_v1_0_get_new_requests_by_exchange_id_list_get(
    limit: conint(ge=1), exchange_id: conint(ge=0) = Query(..., alias='exchangeId')
) -> Union[AutoActivateListResponse, BaseResponse]:
    """
    Get New Requests By Exchange Id List
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-new-requests-on-exchange-list',
    response_model=RefExchangeListResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['BPM activate-phone'],
)
def get_new_requests_on_exchange_list_api_phone_activate_be_v1_0_get_new_requests_on_exchange_list_get(
    limit: conint(ge=1),
) -> Union[RefExchangeListResponse, BaseResponse]:
    """
    Get New Requests On Exchange List
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-ref-exchange-list',
    response_model=RefExchangeListResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_ref_exchange_list_api_phone_activate_be_v1_0_get_ref_exchange_list_get(
    filial_id: int = Query(..., alias='filialId'),
    insert_date_from: Optional[datetime] = Query(None, alias='insertDateFrom'),
    insert_date_to: Optional[datetime] = Query(None, alias='insertDateTo'),
    ref_town_state_id: Optional[int] = Query(None, alias='refTownStateId'),
    ref_vendor_model_id: Optional[int] = Query(None, alias='refVendorModelId'),
    ref_exchange_id_list: Optional[str] = Query(None, alias='refExchangeIdList'),
) -> Union[RefExchangeListResponse, BaseResponse]:
    """
    Get Ref Exchange List
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-ref-town-state-list',
    response_model=RefTownStateList,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_ref_town_state_list_api_phone_activate_be_v1_0_get_ref_town_state_list_get(
    filial_id: int = Query(..., alias='filialId'),
    insert_date_from: Optional[datetime] = Query(None, alias='insertDateFrom'),
    insert_date_to: Optional[datetime] = Query(None, alias='insertDateTo'),
    ref_exchange_id_list: Optional[str] = Query(None, alias='refExchangeIdList'),
) -> Union[RefTownStateList, BaseResponse]:
    """
    Get Ref Town State List
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-ref-vendor-model-list',
    response_model=RefVendorModelList,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_ref_vendor_model_list_api_phone_activate_be_v1_0_get_ref_vendor_model_list_get(
    filial_id: int = Query(..., alias='filialId'),
    insert_date_from: Optional[datetime] = Query(None, alias='insertDateFrom'),
    insert_date_to: Optional[datetime] = Query(None, alias='insertDateTo'),
    ref_town_state_id: Optional[int] = Query(None, alias='refTownStateId'),
    ref_exchange_id_list: Optional[str] = Query(None, alias='refExchangeIdList'),
) -> Union[RefVendorModelList, BaseResponse]:
    """
    Get Ref Vendor Model List
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-reject-reason',
    response_model=RejectReasonList,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_reject_reason_api_phone_activate_be_v1_0_get_reject_reason_get() -> (
    Union[RejectReasonList, BaseResponse]
):
    """
    Get Reject Reason
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-request',
    response_model=PhoneActivateFullResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_phone_activation_request_api_phone_activate_be_v1_0_get_request_get(
    phone_activate_id: conint(ge=0) = Query(..., alias='phoneActivateId')
) -> Union[PhoneActivateFullResponse, BaseResponse]:
    """
    Get Phone Activation Request
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-request-list',
    response_model=PhoneActivateSearchListResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_phone_activation_request_list_api_phone_activate_be_v1_0_get_request_list_get(
    limit: conint(ge=1),
    start_row: conint(ge=1) = Query(..., alias='startRow'),
    filial_id: Optional[int] = Query(None, alias='filialId'),
    entity_id: Optional[int] = Query(None, alias='entityId'),
    entity_spec_id: Optional[int] = Query(None, alias='entitySpecId'),
    customer_account_id: Optional[int] = Query(None, alias='customerAccountId'),
    short_number: Optional[constr(max_length=50)] = Query(None, alias='shortNumber'),
    insert_date_from: Optional[datetime] = Query(None, alias='insertDateFrom'),
    insert_date_to: Optional[datetime] = Query(None, alias='insertDateTo'),
    state_id: Optional[int] = Query(None, alias='stateId'),
    user_login: Optional[str] = Query(None, alias='userLogin'),
    is_fallout: Optional[IsFalloutType] = Query(None, alias='isFallout'),
    ref_exchange_id_list: Optional[str] = Query(None, alias='refExchangeIdList'),
    ref_town_state_id: Optional[int] = Query(None, alias='refTownStateId'),
    ref_vendor_model_id: Optional[int] = Query(None, alias='refVendorModelId'),
) -> Union[PhoneActivateSearchListResponse, BaseResponse]:
    """
    Get Phone Activation Request List
    """
    pass


@app.get(
    '/api/phone-activate-be/v1.0/get-request-list-cnt',
    response_model=CountModel,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def get_phone_activation_request_list_cnt_api_phone_activate_be_v1_0_get_request_list_cnt_get(
    filial_id: Optional[int] = Query(None, alias='filialId'),
    entity_id: Optional[int] = Query(None, alias='entityId'),
    entity_spec_id: Optional[int] = Query(None, alias='entitySpecId'),
    customer_account_id: Optional[int] = Query(None, alias='customerAccountId'),
    short_number: Optional[constr(max_length=50)] = Query(None, alias='shortNumber'),
    insert_date_from: Optional[datetime] = Query(None, alias='insertDateFrom'),
    insert_date_to: Optional[datetime] = Query(None, alias='insertDateTo'),
    state_id: Optional[int] = Query(None, alias='stateId'),
    user_login: Optional[str] = Query(None, alias='userLogin'),
    is_fallout: Optional[IsFalloutType] = Query(None, alias='isFallout'),
    ref_exchange_id_list: Optional[str] = Query(None, alias='refExchangeIdList'),
    ref_town_state_id: Optional[int] = Query(None, alias='refTownStateId'),
    ref_vendor_model_id: Optional[int] = Query(None, alias='refVendorModelId'),
) -> Union[CountModel, BaseResponse]:
    """
    Get Phone Activation Request List Cnt
    """
    pass


@app.post(
    '/api/phone-activate-be/v1.0/manual-execute',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def do_manual_phone_activation_execute_api_phone_activate_be_v1_0_manual_execute_post(
    body: PhoneManualExecuteRequest,
) -> BaseResponse:
    """
    Do Manual Phone Activation Execute
    """
    pass


@app.post(
    '/api/phone-activate-be/v1.0/repeat-auto-activation',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['GUI Flow'],
)
def do_auto_repeat_phone_activation_execute_api_phone_activate_be_v1_0_repeat_auto_activation_post(
    body: PhoneRepeatAutoRequest,
) -> BaseResponse:
    """
    Do Auto Repeat Phone Activation Execute
    """
    pass


@app.post(
    '/api/phone-activate-be/v1.0/request-set-done',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['BPM activate-phone'],
)
def do_phone_activation_request_set_done_api_phone_activate_be_v1_0_request_set_done_post(
    body: PhoneAutomatiSetDoneRequest,
) -> BaseResponse:
    """
    Do Phone Activation Request Set Done
    """
    pass


@app.post(
    '/api/phone-activate-be/v1.0/request-set-fallout',
    response_model=BaseResponse,
    responses={
        '400': {'model': BaseResponse},
        '401': {'model': BaseResponse},
        '403': {'model': BaseResponse},
        '404': {'model': BaseResponse},
        '422': {'model': BaseResponse},
        '500': {'model': BaseResponse},
        '503': {'model': BaseResponse},
    },
    tags=['BPM activate-phone'],
)
def do_phone_activation_request_set_fallout_api_phone_activate_be_v1_0_request_set_fallout_post(
    body: PhoneAutomatiSetFalloutRequest,
) -> BaseResponse:
    """
    Do Phone Activation Request Set Fallout
    """
    pass
