# generated by fastapi-codegen:
#   filename:  api.yaml
#   timestamp: 2023-09-27T16:49:51+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Data(BaseModel):
    lineData: str = Field(
        ...,
        description='Строка линейных данных',
        example='TOWN:727;STATION:40/01; MAN:ECI; OLT:3/00/06/06;ODF:2/08/09/06; LD:ОРШ 223/37: 00/00/1 магистраль/6, 00/00/2 сплиттеры /16, 00/00/2 сплиттеры /18, 00/00/5 распределение/12; ОРКсп 223/37/6/2: 00/00/1х16/11 (Этаж 5); OU:0;ONUPORTNUM:0; (DSL,SIP); 3.542 км',
    )


class TraceOptical(BaseModel):
    data: Data = Field(..., description='Данные ответа')


class TraceCopper(BaseModel):
    townStateId: Optional[int] = Field(
        None, description='Населенный пункт_ID', example=2
    )
    parentContainerExternalId: Optional[int] = Field(
        None,
        description='ID родительского физического контейнера во внешней системе',
        example=13,
    )


class Data1(BaseModel):
    pointLon: str = Field(..., description='Долгота')
    pointLat: str = Field(..., description='Широта')


class BuildingGeoCordsGetResponse(BaseModel):
    data: Data1 = Field(..., description='Данные ответа')
