# generated by fastapi-codegen:
#   filename:  phone-activate-be.yaml
#   timestamp: 2023-10-10T11:40:16+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, conint, constr


class PaSwwCatsAddCfs(BaseModel):
    addCfsSpecName: constr(max_length=100) = Field(
        ...,
        description='Наименование ДВО или Абон. платы, получаем от адаптера',
        examples=['Услуги междугородной и международной связи'],
        title='addCfsSpecName',
    )
    addCfsSpecId: int = Field(
        ...,
        description='Действие над ДВО, получаем от адаптера',
        examples=[141, 142, 140],
        title='addCfsSpecId',
    )
    serviceTypeId: Optional[int] = Field(
        0,
        description='Ид типа сервиса, получаем от адаптера',
        examples=[1],
        title='serviceTypeId',
    )
    updateDate: Optional[datetime] = Field(
        None, description='Дата вызова SWW/CATS', title='dateFrom'
    )


class BaseResponse(BaseModel):
    errCode: Optional[int] = Field(0, description='Код ошибки', title='Errcode')
    errMsg: Optional[str] = Field(None, description='Текст ошибки', title='Errmsg')


class IsCanBeReactivatedType(Enum):
    int_1 = 1
    int_0 = 0


class RefExchange(BaseModel):
    id: int = Field(
        ..., description='Ид станции', examples=[101], title='phoneActivateId'
    )
    name: constr(max_length=255) = Field(
        ...,
        description='Наименование станции',
        examples=['Pavlodar Huawei'],
        title='name',
    )


class BaseCfsActionSpecIdTypeId(Enum):
    int_1 = 1
    int_2 = 2
    int_3 = 3


class AddCfsActionSpecTypeId(Enum):
    int_1 = 1
    int_3 = 3


class IsAutoType(Enum):
    int_1 = 1
    int_0 = 0


class ActivatePhoneProcessTypeId(Enum):
    int_1 = 1
    int_2 = 2


class PaSubscriptionService(BaseModel):
    poElementId: int = Field(
        ...,
        description='Идентификатор элемента',
        examples=[103444],
        title='poElementId',
    )
    poElementName: constr(max_length=255) = Field(
        ...,
        description='Наименование элемента',
        examples=['Услуги междугородной и международной связи'],
        title='poElementName',
    )
    refCfsSpecId: int = Field(
        ...,
        description='Идентификатор действия над позицией 1 - Установка,3 - Снятие',
        examples=[1, 3],
        title='refCfsSpecId',
    )
    isAuto: IsAutoType = Field(
        ...,
        description='Признак автоматической активации, определется через конфигуратор',
        examples=[1, 0],
        title='isAuto',
    )
    serviceCount: int = Field(
        ..., description='Кол-во элементов', examples=[1], title='serviceCount'
    )


class SubscriptionServiceChar(BaseModel):
    charName: constr(max_length=255) = Field(
        ...,
        description='Имя хар-ки',
        examples=['Номер для переадресации (с маской в формате телефонного номера)'],
        title='charName',
    )
    charValue: constr(max_length=4000) = Field(
        ..., description='Значение хар-ки', examples=['3'], title='charValue'
    )


class IsFalloutType(Enum):
    int_1 = 1
    int_0 = 0


class PhoneAssignRequest(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    userLogin: constr(max_length=255) = Field(
        ...,
        description='Пользователь который назначает ',
        examples=['alm-tech'],
        title='userLogin',
    )
    userAssignLogin: constr(max_length=255) = Field(
        ...,
        description='Пользователь кому назначена заявка ',
        examples=['alm-tech'],
        title='userAssignLogin',
    )
    controlDate: Optional[datetime] = Field(
        None, description='Дата контрольного срока', title='controlDate'
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание, если есть ошибка ',
        examples=['Комментарий'],
        title='message',
    )


class PhoneChangeFxsLoginPwd(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    userLogin: constr(max_length=255) = Field(
        ...,
        description='Пользователь который назначает ',
        examples=['alm-tech'],
        title='userLogin',
    )
    fxsLogin: constr(min_length=1, max_length=255) = Field(
        ...,
        description='Логин FXS, в этом методе не обязательный ',
        examples=['7278900108'],
        title='fxsLogin',
    )
    fxsPwd: constr(min_length=1, max_length=255) = Field(
        ..., description='Пароль FXS ', examples=['!@312421412'], title='fxsPwd'
    )


class PhoneManualExecuteRequest(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    feRejectReasonId: Optional[int] = Field(
        ...,
        description='Идентификатор причины отказа',
        examples=[0],
        title='feRejectReasonId',
    )
    resultId: int = Field(
        ..., description='Идентификатор результата', examples=[0], title='resultId'
    )
    userLogin: constr(max_length=255) = Field(
        ...,
        description='Пользователь который назначает ',
        examples=['alm-tech'],
        title='userLogin',
    )
    fxsLogin: Optional[constr(max_length=255)] = Field(
        None, description='Логин FXS ', examples=['7278900108'], title='fxsLogin'
    )
    fxsPwd: Optional[constr(max_length=255)] = Field(
        None, description='Пароль FXS ', examples=['!@312421412'], title='fxsPwd'
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание, если есть ошибка ',
        examples=['Комментарий'],
        title='message',
    )


class PhoneRepeatAutoRequest(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание, если есть ошибка ',
        examples=['Комментарий'],
        title='message',
    )


class PhoneActivateSearch(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    entityId: conint(ge=0) = Field(
        ..., description='Идентификатор сущности', examples=[6000021], title='entityId'
    )
    entitySpecId: int = Field(
        ...,
        description='Идентификатор типа сущности',
        examples=[1, 22],
        title='entitySpecId',
    )
    processTypeId: Optional[ActivatePhoneProcessTypeId] = Field(
        1,
        description='Тип процесса. 1 - Актвиация телефонии и ДВО/Деактивация телефонии и ДВО . 2-Откат актвиация телефонии и ДВО/Откат деактивация телефонии и ДВО',
        examples=[1, 2],
        title='processTypeId',
    )
    stateId: int = Field(
        ..., description='Идентификатор статуса', examples=[0], title='stateId'
    )
    stateName: constr(max_length=100) = Field(
        ..., description='Наименование статуса', examples=['Новый'], title='stateName'
    )
    callBackUrl: constr(max_length=512) = Field(
        ...,
        description='Ссылка на URL, ответа',
        examples=['http://osm'],
        title='callBackUrl',
    )
    createApplicationName: constr(max_length=255) = Field(
        ...,
        description='Приложение создатель ',
        examples=['OSM'],
        title='createApplicationName',
    )
    updateApplicationName: Optional[constr(max_length=255)] = Field(
        '',
        description='Приложение через которое обновили запрос',
        examples=['FE-PHONE'],
        title='updateApplicationName',
    )
    insertDate: Optional[datetime] = Field(
        None, description='Дата создания', title='insertDate'
    )
    updateDate: Optional[datetime] = Field(
        None, description='Дата обновления', title='updateDate'
    )
    controlDate: Optional[datetime] = Field(
        None, description='Контрольный срок. Не используется', title='controlDate'
    )
    assignDate: Optional[datetime] = Field(
        None, description='Дата назначения', title='assignDate'
    )
    userLogin: Optional[constr(max_length=255)] = Field(
        '',
        description='Пользователь кому назначена заявка ',
        examples=['alm-tech'],
        title='userLogin',
    )
    resultId: Optional[int] = Field(
        '', description='Идентификатор результата', examples=[0], title='resultId'
    )
    physicalResource: constr(max_length=50) = Field(
        ...,
        description='Номер базового ресурса. FTTh,ETTh. Транспорт.',
        examples=['8034041'],
        title='physicalResource',
    )
    shortNumber: constr(max_length=50) = Field(
        ...,
        description='Короткий номер Телефона',
        examples=['22653'],
        title='shortNumber',
    )
    oldFullNumber: Optional[constr(max_length=50)] = Field(
        None,
        description='Полный номер Телефона из VCIP',
        examples=['7277422652'],
        title='shortNumber',
    )
    fullNumber: constr(max_length=50) = Field(
        ...,
        description='Полный номер Телефона из VCIP',
        examples=['7277422653'],
        title='fullNumber',
    )
    baseCfsActionSpecId: BaseCfsActionSpecIdTypeId = Field(
        ...,
        description='Действие над базовым ресурсом, 1-Установка, 2-Изменение, 3-Снятие',
        examples=[1, 2, 3],
        title='baseCfsActionSpecId',
    )
    baseCfsActionSpecName: constr(max_length=255) = Field(
        ...,
        description='Наименование действия над базовым ресурсом',
        examples=['Установка'],
        title='baseCfsActionSpecName',
    )
    addressLine: Optional[constr(max_length=255)] = Field(
        None,
        description='Строка адреса',
        examples=['г.Шымкент ул. ТУРКЕСТАНСКАЯ дом 11 кв. 0'],
        title='addressLine',
    )
    customerAccountId: int = Field(
        ...,
        description='Ид лицевого счета',
        examples=[1098881],
        title='customerAccountId',
    )
    customerAccountName: constr(max_length=255) = Field(
        ...,
        description='Наименование лицевого счета',
        examples=['РГП НА ПХВ"ИНЖЕНЕРНО-ТЕХНИЧЕСКИЙ ЦЕНТР ЦЕНТРАЛЬНОЙ...'],
        title='customerAccountName',
    )
    customerAccountNameKZ: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование лицевого счета КЗ',
        examples=['РГП НА ПХВ"ИНЖЕНЕРНО-ТЕХНИЧЕСКИЙ ЦЕНТР ЦЕНТРАЛЬНОЙ...'],
        title='customerAccountNameKZ',
    )
    filialId: int = Field(..., description='Ид филиала', examples=[5], title='filialId')
    filialName: constr(max_length=100) = Field(
        ...,
        description='Наименование филиала',
        examples=['Ю-К ОДТ'],
        title='filialName',
    )
    priorityName: constr(max_length=100) = Field(
        ...,
        description='Наименование приоритета из заказа, категория абонента',
        examples=['Обычный'],
        title='priorityName',
    )
    refTownStateId: Optional[int] = Field(
        -1, description='Id Населенного пункта', examples=[5], title='refTownStateId'
    )
    refTownStateName: Optional[constr(max_length=255)] = Field(
        'Не определено',
        description='Нас. пункт наименование',
        examples=[' г.Шымкент '],
        title='refTownStateName',
    )
    exchangeId: Optional[int] = Field(
        -1, description='Ид ЦАТС/SWW', examples=[5], title='exchangeId'
    )
    exchangeName: Optional[constr(max_length=255)] = Field(
        'Не определено',
        description='Наименование станции',
        examples=['Astana_GTS_SSW_CS2000'],
        title='exchangeName',
    )
    refVendorModelId: Optional[int] = Field(
        -1, description='Ид модели ЦАТС/SWW', examples=[100], title='refVendorModelId'
    )
    refVendorModelName: Optional[constr(max_length=255)] = Field(
        'Не определено',
        description='Наименование модели ЦАТС/SWW',
        examples=['Genband CS2000C'],
        title='refVendorModelName',
    )
    adapterUrl: Optional[constr(max_length=512)] = Field(
        'Не определено',
        description='adapterUrl - Ссылка для команд на станцию. REST API',
        examples=[
            'http://10.8.26.66:7733/api/activate-resource-phone-adapter-be/v0.1/order'
        ],
        title='adapterUrl',
    )
    isFallout: Optional[IsFalloutType] = Field(
        0,
        description='Если 1, то сразу на ручную работу заказ SWW/ЦАТС',
        examples=[0, 1],
        title='isFallout',
    )
    feRejectReasonId: Optional[int] = Field(
        ...,
        description='Идентификатор причины отказа',
        examples=[0],
        title='feRejectReasonId',
    )
    feRejectReasonName: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование причины отказа ',
        examples=['Нет'],
        title='feRejectReasonName',
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание, если есть ошибка ',
        examples=[
            'Не указаны cramer_switch_container_id/ssw_cust_group_id для global_number=7184090512 error_message=None local_number=90512 ssw_cust_group_id=None cramer_switch_container_id=None pool_id=140749 pool_name=90512-90512 service_type_id=18 base_resource_spec_id=1005005 ref_town_state_id=10608 status=used в ответе сервиса VCIP.'
        ],
        title='message',
    )
    fxsLogin: Optional[constr(max_length=255)] = Field(
        None,
        description='Логин FXS, в этом методе не обязательный ',
        examples=['7278900108'],
        title='fxsLogin',
    )
    fxsPwd: Optional[constr(max_length=255)] = Field(
        None, description='Пароль FXS ', examples=['!@312421412'], title='fxsPwd'
    )


class CountModel(BaseModel):
    count: int = Field(..., description='Кол-во записей', examples=[0], title='count')


class PhoneActivateHistory(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию  ',
        examples=[101],
        title='phoneActivateId',
    )
    userLogin: Optional[constr(max_length=255)] = Field(
        None,
        description='Пользователь кому назначена заявка ',
        examples=['alm-tech'],
        title='userLogin',
    )
    stateId: int = Field(
        ..., description='Идентификатор статуса', examples=[0], title='stateId'
    )
    stateName: constr(max_length=255) = Field(
        ..., description='Наименование статуса', examples=['Новый'], title='stateName'
    )
    insertDate: Optional[datetime] = Field(
        None, description='Дата создания', title='insertDate'
    )
    comment: Optional[constr(max_length=4000)] = Field(
        ...,
        description='Примечание пользователя ',
        examples=['Выполнено вручную'],
        title='comment',
    )


class RejectReason(BaseModel):
    id: int = Field(
        ..., description='Ид причины отказа ', examples=[101], title='rejectReasonId'
    )
    name: constr(max_length=255) = Field(
        ...,
        description='Наименование причины отказа',
        examples=['alm-tech'],
        title='userLogin',
    )
    nameKz: constr(max_length=255) = Field(
        ...,
        description='Наименование причины отказа. На казахском языке',
        examples=['alm-tech'],
        title='userAssignLogin',
    )


class RefTownState(BaseModel):
    id: int = Field(
        ...,
        description='Ид населенного пункта ',
        examples=[101],
        title='refTownStateId',
    )
    name: constr(max_length=255) = Field(
        ...,
        description='Наименование населенного пункта  ',
        examples=['alm-tech'],
        title='name',
    )


class RefVendorModel(BaseModel):
    id: int = Field(
        ..., description='Ид модели ЦАТС/SWW', examples=[101], title='refVendorModelId'
    )
    name: constr(max_length=255) = Field(
        ...,
        description='Наименование модели ЦАТС/SWW ',
        examples=['alm-tech'],
        title='name',
    )


class PhoneAutomatiSetDoneRequest(BaseModel):
    phoneActivateId: int = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    fxsLogin: Optional[constr(max_length=255)] = Field(
        None, description='Логин FXS ', examples=['7278900108'], title='fxsLogin'
    )
    fxsPwd: Optional[constr(max_length=255)] = Field(
        None, description='Пароль FXS ', examples=['!@312421412'], title='fxsPwd'
    )
    paSwwCatsAddCfsItems: Optional[List[PaSwwCatsAddCfs]] = Field(
        None,
        description='Точный набор ДВО на оборудовании',
        title='Paswwcatsaddcfsitems',
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание от BPM Активации телефонии',
        examples=['Примечание от BPM Активации телефонии'],
        title='message',
    )


class PhoneAutomatiSetFalloutRequest(BaseModel):
    phoneActivateId: int = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    fxsLogin: Optional[constr(max_length=255)] = Field(
        None,
        description='Логин FXS, в этом методе не обязательный ',
        examples=['7278900108'],
        title='fxsLogin',
    )
    fxsPwd: Optional[constr(max_length=255)] = Field(
        None, description='Пароль FXS ', examples=['!@312421412'], title='fxsPwd'
    )
    paSwwCatsAddCfsItems: Optional[List[PaSwwCatsAddCfs]] = Field(
        None,
        description='Точный набор ДВО на оборудовании',
        title='Paswwcatsaddcfsitems',
    )
    isCanBeReactivated: IsCanBeReactivatedType = Field(
        ...,
        description='Если 1, дает возможность повторной активации',
        examples=[0, 1],
        title='isCanBeReactivated',
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Текст ошибки от BPM Активации телефонии',
        examples=['Текст ошибки от BPM Активации телефонии'],
        title='message',
    )


class RefExchangeListResponse(BaseModel):
    refExchangeList: Optional[List[RefExchange]] = Field(
        None, description='Список станций', title='Refexchangelist'
    )


class PaOrderAddFs(BaseModel):
    poElementId: int = Field(
        ...,
        description='Идентификатор элемента',
        examples=[1534886],
        title='poElementId',
    )
    poElementName: constr(max_length=255) = Field(
        ...,
        description='Наименование элемента',
        examples=['Услуги междугородной и международной связи'],
        title='callBackUrl',
    )
    addCfsActionSpecId: AddCfsActionSpecTypeId = Field(
        ...,
        description='Идентификатор действия над позицией 1 - Установка,3 - Снятие',
        examples=[1, 3],
        title='addCfsActionSpecId',
    )
    addCfsSpecName: constr(max_length=100) = Field(
        ...,
        description='Наименование ДВО или Абон. платы',
        examples=['Услуги междугородной и международной связи'],
        title='addCfsSpecName',
    )
    refCfsSpecId: int = Field(
        ...,
        description='Идентификатор ДВО',
        examples=[141, 142, 140],
        title='refCfsSpecId',
        
    )
    isAuto: IsAutoType = Field(
        ...,
        description='Признак автоматической активации, определется через конфигуратор',
        examples=[1, 0],
        title='isAuto',
    )
    serviceCount: int = Field(
        ..., description='Кол-во элементов', examples=[1], title='serviceCount'
    )
    dateFrom: Optional[datetime] = Field(
        None, description='Дата начала действия услуги', title='dateFrom'
    )


class PhoneActivateRequest(BaseModel):
    entityId: conint(ge=0) = Field(
        ..., description='Идентификатор сущности', examples=[6000021], title='entityId'
    )
    entitySpecId: int = Field(
        ...,
        description='Идентификатор типа сущности',
        examples=[1, 22],
        title='entitySpecId',
    )
    processTypeId: Optional[ActivatePhoneProcessTypeId] = Field(
        1,
        description='Тип процесса. 1 - Актвиация телефонии и ДВО/Деактивация телефонии и ДВО . 2-Откат актвиация телефонии и ДВО/Откат деактивация телефонии и ДВО',
        examples=[1, 2],
        title='processTypeId',
    )
    callBackUrl: constr(max_length=255) = Field(
        ...,
        description='Ссылка на URL, ответа',
        examples=['http://osm'],
        title='callBackUrl',
    )
    createApplicationName: constr(max_length=255) = Field(
        ...,
        description='Приложение создатель ',
        examples=['OSM'],
        title='createApplicationName',
    )
    physicalResource: constr(max_length=50) = Field(
        ...,
        description='Номер базового ресурса. FTTh,ETTh. Транспорт.',
        examples=['8034041'],
        title='physicalResource',
    )
    shortNumber: constr(max_length=50) = Field(
        ...,
        description='Короткий номер Телефона',
        examples=['22653'],
        title='shortNumber',
    )
    oldFullNumber: Optional[constr(max_length=50)] = Field(
        None,
        description='Полный номер Телефона из VCIP',
        examples=['7277422652'],
        title='shortNumber',
    )
    fullNumber: constr(max_length=50) = Field(
        ...,
        description='Полный номер Телефона из VCIP',
        examples=['7277422653'],
        title='fullNumber',
    )
    baseCfsActionSpecId: BaseCfsActionSpecIdTypeId = Field(
        ...,
        description='Действие над базовым ресурсом, 1-Установка, 2-Изменение, 3-Снятие',
        examples=[1, 2, 3],
        title='baseCfsActionSpecId',
    )
    baseCfsActionSpecName: constr(max_length=255) = Field(
        ...,
        description='Наименование действия над базовым ресурсом',
        examples=['Установка'],
        title='baseCfsActionSpecName',
    )
    addressLine: constr(max_length=255) = Field(
        ...,
        description='Строка адреса',
        examples=['г.Шымкент ул. ТУРКЕСТАНСКАЯ дом 11 кв. 0'],
        title='addressLine',
    )
    customerAccountId: int = Field(
        ...,
        description='Ид лицевого счета',
        examples=[1098881],
        title='customerAccountId',
    )
    customerAccountName: constr(max_length=255) = Field(
        ...,
        description='Наименование лицевого счета',
        examples=['РГП НА ПХВ"ИНЖЕНЕРНО-ТЕХНИЧЕСКИЙ ЦЕНТР ЦЕНТРАЛЬНОЙ...'],
        title='customerAccountName',
    )
    customerAccountNameKZ: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование лицевого счета КЗ',
        examples=['РГП НА ПХВ"ИНЖЕНЕРНО-ТЕХНИЧЕСКИЙ ЦЕНТР ЦЕНТРАЛЬНОЙ...'],
        title='customerAccountNameKZ',
    )
    filialId: int = Field(..., description='Ид филиала', examples=[5], title='filialId')
    filialName: constr(max_length=100) = Field(
        ...,
        description='Наименование филиала',
        examples=['Ю-К ОДТ'],
        title='filialName',
    )
    paOrderAddСfsItems: Optional[List[PaOrderAddFs]] = Field(
        None, description='Массив команд для оборудования', title='Paorderaddсfsitems'
    )
    paSubscriptionServiceItemsOld: Optional[List[PaSubscriptionService]] = Field(
        None,
        description='Текущий состав подписки. ДВО и Абон платы. При новом заказе пусто',
        title='Pasubscriptionserviceitemsold',
    )
    paSubscriptionServiceItemsNew: Optional[List[PaSubscriptionService]] = Field(
        None,
        description='Новый состав подписки. ДВО и Абон платы. При снятие пусто ',
        title='Pasubscriptionserviceitemsnew',
    )
    subscriptionServiceCharList: Optional[List[SubscriptionServiceChar]] = Field(
        None, description='Список хар-тик', title='subscriptionServiceCharList'
    )
    priorityName: constr(max_length=100) = Field(
        ...,
        description='Наименование приоритета из заказа, категория абонента',
        examples=['Обычный'],
        title='priorityName',
    )
    refTownStateId: Optional[int] = Field(
        -1, description='Id Населенного пункта', examples=[5], title='refTownStateId'
    )
    refTownStateName: Optional[constr(max_length=255)] = Field(
        'Не определено',
        description='Нас. пункт наименование',
        examples=[' г.Шымкент '],
        title='refTownStateName',
    )
    exchangeId: Optional[int] = Field(
        -1, description='Ид ЦАТС/SWW', examples=[5], title='exchangeId'
    )
    exchangeName: Optional[constr(max_length=255)] = Field(
        'Не определено',
        description='Наименование станции',
        examples=['Astana_GTS_SSW_CS2000'],
        title='exchangeName',
    )
    refVendorModelId: Optional[int] = Field(
        -1, description='Id модели ЦАТС/SWW', examples=[100], title='refVendorModelId'
    )
    refVendorModelName: Optional[constr(max_length=255)] = Field(
        'Не определено',
        description='Наименование модели ЦАТС/SWW',
        examples=['Genband CS2000C'],
        title='refVendorModelName',
    )
    adapterUrl: Optional[constr(max_length=512)] = Field(
        None,
        description='adapterUrl - Ссылка для команд на станцию. REST API',
        examples=[
            'http://10.8.26.66:7733/api/activate-resource-phone-adapter-be/v0.1/order'
        ],
        title='adapterUrl',
    )
    isFallout: IsFalloutType = Field(
        ...,
        description='Если 1, то сразу на ручную работу заказ SWW/ЦАТС',
        examples=[0, 1],
        title='isFallout',
    )
    isCanBeReactivated: Optional[IsCanBeReactivatedType] = Field(
        0,
        description='Если 1, дает возможность повторной активации',
        examples=[0, 1],
        title='isCanBeReactivated',
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание, если есть ошибка ',
        examples=[
            'Не указаны cramer_switch_container_id/ssw_cust_group_id для global_number=7184090512 error_message=None local_number=90512 ssw_cust_group_id=None cramer_switch_container_id=None pool_id=140749 pool_name=90512-90512 service_type_id=18 base_resource_spec_id=1005005 ref_town_state_id=10608 status=used в ответе сервиса VCIP.'
        ],
        title='message',
    )
    positionId: Optional[str] = Field(
        ...,
        description='Идентификатор позиции',
        examples=[1808077001],
        title='positionId',
    )


class PhoneActivateFullResponse(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    entityId: conint(ge=0) = Field(
        ..., description='Идентификатор сущности', examples=[6000021], title='entityId'
    )
    entitySpecId: int = Field(
        ...,
        description='Идентификатор типа сущности',
        examples=[1, 22],
        title='entitySpecId',
    )
    processTypeId: Optional[ActivatePhoneProcessTypeId] = Field(
        1,
        description='Тип процесса. 1 - Актвиация телефонии и ДВО/Деактивация телефонии и ДВО . 2-Откат актвиация телефонии и ДВО/Откат деактивация телефонии и ДВО',
        examples=[1, 2],
        title='processTypeId',
    )
    stateId: int = Field(
        ..., description='Идентификатор статуса', examples=[0], title='stateId'
    )
    stateName: constr(max_length=100) = Field(
        ..., description='Наименование статуса', examples=['Новый'], title='stateName'
    )
    callBackUrl: constr(max_length=512) = Field(
        ...,
        description='Ссылка на URL, ответа',
        examples=['http://osm'],
        title='callBackUrl',
    )
    createApplicationName: constr(max_length=255) = Field(
        ...,
        description='Приложение создатель ',
        examples=['OSM'],
        title='createApplicationName',
    )
    updateApplicationName: Optional[constr(max_length=255)] = Field(
        None,
        description='Приложение через которое обновляли запрос',
        examples=['FE-PHONE'],
        title='updateApplicationName',
    )
    insertDate: Optional[datetime] = Field(
        None, description='Дата создания', title='insertDate'
    )
    updateDate: Optional[datetime] = Field(
        None, description='Дата обновления', title='updateDate'
    )
    controlDate: Optional[datetime] = Field(
        None, description='Контрольный срок. Не используется', title='controlDate'
    )
    assignDate: Optional[datetime] = Field(
        None, description='Дата назначения', title='assignDate'
    )
    userLogin: Optional[constr(max_length=255)] = Field(
        None,
        description='Пользователь кому назначена заявка ',
        examples=['alm-tech'],
        title='userLogin',
    )
    resultId: int = Field(
        ..., description='Идентификатор результата', examples=[0], title='resultId'
    )
    physicalResource: constr(max_length=50) = Field(
        ...,
        description='Номер базового ресурса. FTTh,ETTh. Транспорт.',
        examples=['8034041'],
        title='physicalResource',
    )
    shortNumber: constr(max_length=50) = Field(
        ...,
        description='Короткий номер Телефона',
        examples=['22653'],
        title='shortNumber',
    )
    oldFullNumber: Optional[constr(max_length=50)] = Field(
        None,
        description='Полный номер Телефона из VCIP',
        examples=['7277422652'],
        title='shortNumber',
    )
    fullNumber: constr(max_length=50) = Field(
        ...,
        description='Полный номер Телефона из VCIP',
        examples=['7277422653'],
        title='fullNumber',
    )
    baseCfsActionSpecId: BaseCfsActionSpecIdTypeId = Field(
        ...,
        description='Действие над базовым ресурсом, 1-Установка, 2-Изменение, 3-Снятие',
        examples=[1, 2, 3],
        title='baseCfsActionSpecId',
    )
    baseCfsActionSpecName: constr(max_length=255) = Field(
        ...,
        description='Наименование действия над базовым ресурсом',
        examples=['Установка'],
        title='baseCfsActionSpecName',
    )
    addressLine: constr(max_length=255) = Field(
        ...,
        description='Строка адреса',
        examples=['г.Шымкент ул. ТУРКЕСТАНСКАЯ дом 11 кв. 0'],
        title='addressLine',
    )
    customerAccountId: int = Field(
        ...,
        description='Ид лицевого счета',
        examples=[1098881],
        title='customerAccountId',
    )
    customerAccountName: constr(max_length=255) = Field(
        ...,
        description='Наименование лицевого счета',
        examples=['РГП НА ПХВ"ИНЖЕНЕРНО-ТЕХНИЧЕСКИЙ ЦЕНТР ЦЕНТРАЛЬНОЙ...'],
        title='customerAccountName',
    )
    customerAccountNameKZ: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование лицевого счета КЗ',
        examples=['РГП НА ПХВ"ИНЖЕНЕРНО-ТЕХНИЧЕСКИЙ ЦЕНТР ЦЕНТРАЛЬНОЙ...'],
        title='customerAccountNameKZ',
    )
    filialId: int = Field(..., description='Ид филиала', examples=[5], title='filialId')
    filialName: constr(max_length=100) = Field(
        ...,
        description='Наименование филиала',
        examples=['Ю-К ОДТ'],
        title='filialName',
    )
    paOrderAddCfsItems: Optional[List[PaOrderAddFs]] = Field(
        None,
        description='Массив команд для оборудования',
        min_items=1,
        title='Paorderaddcfsitems',
    )
    paSubscriptionServiceItemsOld: Optional[List[PaSubscriptionService]] = Field(
        None,
        description='Текущий состав подписки. ДВО и Абон платы. При новом заказе пусто',
        title='Pasubscriptionserviceitemsold',
    )
    paSubscriptionServiceItemsNew: Optional[List[PaSubscriptionService]] = Field(
        None,
        description='Новый состав подписки. ДВО и Абон платы. При снятие пусто ',
        title='Pasubscriptionserviceitemsnew',
    )
    paSwwCatsAddCfsItems: Optional[List[PaSwwCatsAddCfs]] = Field(
        None,
        description='Точный набор ДВО на оборудовании',
        title='Paswwcatsaddcfsitems',
    )
    priorityName: constr(max_length=100) = Field(
        ...,
        description='Наименование приоритета из заказа, категория абонента',
        examples=['Обычный'],
        title='priorityName',
    )
    refTownStateId: Optional[int] = Field(
        None, description='Id Населенного пункта', examples=[5], title='refTownStateId'
    )
    refTownStateName: Optional[constr(max_length=255)] = Field(
        None,
        description='Нас. пункт наименование',
        examples=[' г.Шымкент '],
        title='refTownStateName',
    )
    exchangeId: Optional[int] = Field(
        None, description='Ид ЦАТС/SWW', examples=[5], title='exchangeId'
    )
    exchangeName: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование станции',
        examples=['Astana_GTS_SSW_CS2000'],
        title='exchangeName',
    )
    refVendorModelId: Optional[int] = Field(
        None, description='Ид модели ЦАТС/SWW', examples=[100], title='refVendorModelId'
    )
    refVendorModelName: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование модели ЦАТС/SWW',
        examples=['Genband CS2000C'],
        title='refVendorModelName',
    )
    adapterUrl: Optional[constr(max_length=512)] = Field(
        None,
        description='adapterUrl - Ссылка для команд на станцию. REST API',
        examples=[
            'http://10.8.26.66:7733/api/activate-resource-phone-adapter-be/v0.1/order'
        ],
        title='adapterUrl',
    )
    isFallout: IsFalloutType = Field(
        ...,
        description='Если 1, то сразу на ручную работу заказ SWW/ЦАТС',
        examples=[0, 1],
        title='isFallout',
    )
    feRejectReasonId: Optional[int] = Field(
        None,
        description='Идентификатор причины отказа',
        examples=[0],
        title='feRejectReasonId',
    )
    feRejectReasonName: Optional[constr(max_length=255)] = Field(
        None,
        description='Наименование причины отказа ',
        examples=['Нет'],
        title='feRejectReasonName',
    )
    message: Optional[constr(max_length=4000)] = Field(
        None,
        description='Примечание, если есть ошибка ',
        examples=[
            'Не указаны cramer_switch_container_id/ssw_cust_group_id для global_number=7184090512 error_message=None local_number=90512 ssw_cust_group_id=None cramer_switch_container_id=None pool_id=140749 pool_name=90512-90512 service_type_id=18 base_resource_spec_id=1005005 ref_town_state_id=10608 status=used в ответе сервиса VCIP.'
        ],
        title='message',
    )
    fxsLogin: Optional[constr(max_length=255)] = Field(
        None,
        description='Логин FXS, в этом методе не обязательный ',
        examples=['7278900108'],
        title='fxsLogin',
    )
    fxsPwd: Optional[constr(max_length=255)] = Field(
        None, description='Пароль FXS ', examples=['!@312421412'], title='fxsPwd'
    )
    isCanBeReactivated: Optional[IsCanBeReactivatedType] = Field(
        None,
        description='Если 1, дает возможность повторной активации',
        examples=[0, 1],
        title='isCanBeReactivated',
    )


class PhoneActivateSearchListResponse(BaseModel):
    phoneActivateSearchListResponse: List[PhoneActivateSearch] = Field(
        ...,
        description='Ответ для формы поиска',
        title='Phoneactivatesearchlistresponse',
    )


class PhoneActivateHistoryListResponse(BaseModel):
    phoneActivateHistoryResponseList: List[PhoneActivateHistory] = Field(
        ...,
        description='Ответ для формы поиска',
        title='Phoneactivatehistoryresponselist',
    )


class RejectReasonList(BaseModel):
    rejectReasonList: Optional[List[RejectReason]] = Field(
        None, description='Список причин отказа', title='Rejectreasonlist'
    )


class RefTownStateList(BaseModel):
    refTownStateList: Optional[List[RefTownState]] = Field(
        None, description='Список причин отказа', title='Reftownstatelist'
    )


class RefVendorModelList(BaseModel):
    refVendorModelList: Optional[List[RefVendorModel]] = Field(
        None, description='Список моделий ЦАТС/SWW', title='Refvendormodellist'
    )


class AutoActivate(BaseModel):
    phoneActivateId: conint(ge=0) = Field(
        ...,
        description='Ид заявки на активацию ',
        examples=[101],
        title='phoneActivateId',
    )
    fullNumber: constr(max_length=50) = Field(
        ...,
        description='Полный номер Телефона из VCIP',
        examples=['7277422653'],
        title='fullNumber',
    )
    exchangeId: int = Field(
        ..., description='Ид ЦАТС/SWW', examples=[5], title='exchangeId'
    )
    refVendorModelId: int = Field(
        ..., description='Ид модели ЦАТС/SWW', examples=[100], title='refVendorModelId'
    )
    adapterUrl: constr(max_length=512) = Field(
        ...,
        description='adapterUrl - Ссылка для команд на станцию. REST API',
        examples=[
            'http://10.8.26.66:7733/api/activate-resource-phone-adapter-be/v0.1/order'
        ],
        title='adapterUrl',
    )
    entityId: conint(ge=0) = Field(
        ..., description='Идентификатор сущности', examples=[6000021], title='entityId'
    )
    entitySpecId: int = Field(
        ...,
        description='Идентификатор типа сущности',
        examples=[1, 22],
        title='entitySpecId',
    )
    baseCfsActionSpecId: BaseCfsActionSpecIdTypeId = Field(
        ...,
        description='Действие над базовым ресурсом, 1-Установка, 2-Изменение, 3-Снятие',
        examples=[1, 2, 3],
        title='baseCfsActionSpecId',
    )
    paOrderAddCfsItems: Optional[List[PaOrderAddFs]] = Field(
        None,
        description='Массив команд на оборудовании. ДВО',
        title='Paorderaddcfsitems',
    )


class PhoneActivateListRequest(BaseModel):
    phoneActivateList: List[PhoneActivateRequest] = Field(
        ...,
        description='Массив данных Ключ/Значение',
        max_items=2,
        min_items=1,
        title='Phoneactivatelist',
    )


class AutoActivateListResponse(BaseModel):
    autoActivatetListResponse: List[AutoActivate] = Field(
        ...,
        description='Список заявок для обработки BPM',
        title='Autoactivatetlistresponse',
    )
