openapi: 3.0.0
x-stoplight:
  id: xqtekkae6enj4
info:
  title: Адаптер конфигурации ресурсов телефонии
  version: '1.0'
  contact:
    name: Samat
    email: samat@telecom.kz
    url: telecom.kz
  description: Адаптер конфигурации ресурсов телефонии
servers:
  - url: 'http://localhost:3000/api/v1.0/activate-resource-phone-adapter-be'
paths:
  /order:
    parameters: []
    post:
      summary: ''
      operationId: post-order
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Структура заказа на исполнение команды
              properties:
                entity_id:
                  type: integer
                  description: id заказа
                entity_spec_id:
                  type: integer
                  description: id спецификации заказа
                full_number:
                  type: string
                  description: полный номер телефона
                local_number:
                  type: string
                  description: местный номер телефона
                actions:
                  type: array
                  minItems: 1
                  description: Список идентификаторов BASE_CFS_ACTION_SPEC
                  items:
                    type: integer
                exchange:
                  $ref: '#/components/schemas/exchange'
                custgroup:
                  $ref: '#/components/schemas/custgroup'
              required:
                - entity_id
                - entity_spec_id
                - full_number
                - local_number
                - actions
                - exchange
        description: Заказ на исполнение команды
      description: Заказ на исполнение команды
      tags:
        - post order
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: integer
                  error_msg:
                    type: string
                  result:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      properties:
                        action_id:
                          type: integer
                        action_result:
                          type: object
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
components:
  schemas:
    exchange:
      title: exchange
      x-stoplight:
        id: k5tu08jp0y6k0
      type: object
      description: Станция
      properties:
        id:
          type: integer
          description: Идентификатор станции
        external_id:
          type: integer
          description: id станции в системе тех. учета
        town_state_id:
          type: integer
          description: Идентификатор населенного пункта
        exchange_state_id:
          type: integer
          description: Статус станции
        vendor_model_id:
          type: integer
          description: Идентификатор модели оборудования
        hostname:
          type: string
          description: Название станции
        description_ru:
          type: string
          description: Описание на русском языке
        description_kz:
          type: string
          description: Описание на казахском языке
        url:
          type: string
          description: Строка подключения
        is_activate_auto:
          type: boolean
          description: Признак автоматической активации
      required:
        - id
        - external_id
        - town_state_id
        - exchange_state_id
        - vendor_model_id
        - hostname
        - description_ru
        - description_kz
        - url
        - is_activate_auto
    custgroup:
      title: custgroup
      x-stoplight:
        id: 4jmta12g1jur5
      type: object
      description: Группа
      properties:
        id:
          type: number
          description: Идентификатор группы
        name:
          type: string
          description: Название группы
        custgroup_state_id:
          type: number
          description: Статус группы
        is_mn_domain_use:
          type: boolean
          description: Признак использования MN DOMAIN
        mn_domain:
          type: string
          description: MN DOMAIN
        is_node_use:
          type: boolean
          description: Признак использования NODE
        node:
          type: string
          description: NODE
        is_call_source_code_use:
          type: boolean
          description: Признак использования CALL SOURCE CODE
        call_source_code:
          type: number
          description: CALL SOURCE CODE
        is_local_dn_set_use:
          type: boolean
          description: Признак использования LOCAL DN SET
        local_dn_set:
          type: integer
          description: LOCAL DN SET
        is_imsi_prefix_use:
          type: boolean
          description: Признак использования IMSI PREFIX
        imsi_prefix:
          type: integer
          description: IMSI PREFIX
      required:
        - id
        - name
        - custgroup_state_id
    command:
      title: command
      x-stoplight:
        id: 2be9db2ba7044
      type: object
      description: Список команд
      properties:
        id:
          type: integer
          description: Идентификатор команды
        order_num:
          type: number
          description: Шаг исполнения команды
        name:
          type: string
          description: Описание команды
        code:
          type: string
          description: Команда
      required:
        - id
        - order_num
        - name
        - code
  responses: {}
tags:
  - name: post order
    description: Отправка задания адаптеру активации сервисов телефонии

